### ISSUE TITLE
Invalid webhook supplied

### ISSUE THREAD

**Issue by mamisano** [thinkst/canarytokens#11]
@thinkst 
I am having an issue when trying to use a Slack webhook. I receive the error message "Invalid web hook supplied". BTW, nice upgrade with the error reporting... the web page used to just hang and not tell me what was going on, lol. 

That being said, what is the required syntax for webhooks?

**Comment by thinkst** [comment]
@mamisano Sorry for the delayed response. Unfortunately, the slack webhook isn't supported yet but it is on the roadmap. Since there is a python client, it could easily be added to channel_output_webhook.py. Some checks would need to be put in place for the type of webhook too. We would welcome a pull request integrating this functionality ;)
