### ISSUE TITLE
Token Triggered on StartUp

### ISSUE THREAD

**Issue by shinkuan** [thinkst/canarytokens#143]
**Description**: I have a folder which is generated using [https://canarytokens.org/generate](url), and it was placed on desktop folder. The token always triggered when I startup my PC. When PC is idle on desktop, it triggers the token every 5 to 10 minutes.

**What I have tried**: Disabled almost everything that runs on startup but won't effect Windows system using Autorun.exe from microsoft. 
Moving the folder to other folder caused the token triggered, but after the folder moved to other folder (ex: Documents), it doesn't get triggered on startup. However, the folder moved to Documents gets triggered whenever I open Documents folder.

**To reproduce**: Generate a Folder Token using [https://canarytokens.org/generate](url) and place it on desktop. Windows systen is latest 21H2.

I think this is because Windows File Explorer checking every subfolder in the folder you are browsing, but I can't 100% confirm that is true.

Is anyone know what thing is kept opening my folders and how can I avoid this false detection?

**Comment by jayjb** [comment]
Hi @shinkuan,

Thanks for writing in. The Windows Folder Canarytoken uses a DNS trigger so once it has been triggered once, its advised to change it out because in the past we have seen dns requests being cached. 

Putting the Windows Folder token on the desktop will probably cause false alerts. The reason is that Windows Explorer and Quick Access do some caching of popular used directories. This may be causing them to do some background processing of the `ini`.
