### ISSUE TITLE
Simple explanation of files

### ISSUE THREAD

**Issue by veeral-patel** [thinkst/canarytokens#32]
Hi, I wanted to contribute to the project but don't understand how the code is structured...if you get a chance, can you document that? Thanks!

**Comment by thinkst** [comment]
hey @veeral-patel,

We always appreciate contributions to your projects. Is there a particular part of the code you would like documented?

**Comment by veeral-patel** [comment]
Specifically, I was wondering how Canarytokens detects if a Word doc is opened, and sends that information to the server

**Comment by thinkst** [comment]
Hey @veeral-patel,

If a computer is completely offline, then there will not be any communication; however if the computer that is opening the tokened Word document simply denies outgoing HTTP traffic, the communication will get out because we are using a DNS token for MS Word documents.

In terms of how we do this, I think it would be best to read through the code in `msword.py` in this repo. As an overview, we simply insert an an image with a `URL` reference. We then replace that `URL` with your canarytoken. When someone opens the Word document, that `URL` or now your canarytoken url, is hit trying to get the image. 

Please let me know if you have any other questions

**Comment by jayjb** [comment]
Hey @veeral-patel,

Im closing this issue for now (ive made a note to explain more of our stuff on the wiki). Please reopen if you have any further questions or create a new issue if you have any new questions.
