### ISSUE TITLE
URL switches back and forth after change.

### ISSUE THREAD

**Issue by s3c** [thinkst/canarytokens#34]
Initially when I filled the config files, I made a mistake in the domain. After changing it to the correct domain it however still points to the old one most of the time, with the occasional token being generated with the correct one specified in the config file. Is there some sort of cache somewhere that can be cleared?

**Comment by thinkst** [comment]
Hey @s3c,

Yip you spot on. So basically when we start the canarytokens server up, we run a script that updates settings from the config files into our redis database.

In this case, the `CANARY_DOMAINS` environment variable is stored as a set in redis and so we simply add to the setup. This does mean that old domains are still present. 

In order to remove them, once your canarytokens docker server is up and running, you can use `docker exec -ti redis redis-cli` to be able to check what data your canarytokens server has. 

You can quickly check which domains are stored in redis now with `SMEMBERS canary_domains`. If you see one that you want to remove, you can use `SREM canary_domains <key>` where `<key>` is the domain you want removed. 

Please let me know if this helped.

**Comment by jayjb** [comment]
Hey @s3c,

Im closing this issue; please reopen if you are still having a problem with it.
