### ISSUE TITLE
Support IP2Location.io API

### ISSUE THREAD

**Issue by ip2location** [thinkst/canarytokens#343]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add IP2Location.io API.

**Describe alternatives you've considered**
-.

**Additional context**
IP2Location.io API could be a good alternative geolocation provider to provide users with more choices. It provides basic information such as country, region, city, latitude and longitude, ASN and AS, and WHOIS information for a domain. 

User can sign up for a free API key, or use the keyless API to get started. There is a limit of 500 free queries per day without an API key. If using an API key with the free plan, users can perform 30,000 queries per month.

For more information, you can check our documentation at https://www.ip2location.io/ip2location-documentation. Hope you can consider adding this API as an option into your project.

**Comment by jayjb** [comment]
Hi @ip2location,

Thanks for writing in. We haven't considered a different IP location service mostly because we haven't had any issues with the currently used one. That said, we would be happy to accept a PR extending Canarytokens to use ip2location.io as well. It does look like a good alternative. 

If you would like some help with a PR, i'd be happy to guide you along.

**Comment by ip2location** [comment]
Hi @jayjb,

We can create a PR for this, but how should we get started? I saw that the documentation is recommending to use Canarytokens with the docker, can we have a small guidance on how to do it for developing? Thanks for the reply.
