### ISSUE TITLE
CanaryTokens - Detection Bypass (PDF)

### ISSUE THREAD

**Issue by GIJohnathan** [thinkst/canarytokens#36]
Please confirm and fix these issues, also I'd really like a version number.

Reported by Gionathan Armando Reale

#####################################################################

Identification:

Due to size/metadata/timestamp being very limited in variation it is easily possible to detect which PDF documents are likely to contain CanaryTokens.

Detection Bypass:

Opening a PDF document containing a CanaryToken using Foxit Reader 9.4.1.16xxx will allow you to view the file (and the CanaryToken hidden url) without triggering the CanaryToken. Other PDF document viewers may also bypass detection

**Comment by GIJohnathan** [comment]
![imageedit_2_3057874925](https://user-images.githubusercontent.com/33219238/54282647-bb3c0b80-459c-11e9-8cbb-d7dda43301d1.gif)

**Comment by thinkst** [comment]
Thanks for taking the time to test Canarytokens.

The PDF token works due to a quirk in Adobe Reader, which gets the alert off before the user is prompted to allow the network connection. This why the token type is listed as "Acrobat Reader PDF Document – Get alerted when a PDF document is opened in Acrobat Reader". We're not aware of a similar trick which works on Foxit Reader, though the document has worked on certain versions of Chrome's builtin PDF reader.

We're open to pull requests if you've got insight on how to replicate this behaviour with Foxit Reader.

**Comment by GIJohnathan** [comment]
That makes a lot of sense, you can close this issue now 👍

**Comment by thinkst** [comment]
Glad we could clear it up.
