### ISSUE TITLE
[BUG] Invalid Canarytoken triggered alerts received

### ISSUE THREAD

**Issue by cyb3n3tic** [thinkst/canarytokens#447]
**Describe the bug**
I created a sensitive command token based on whois command and tested successfully with an alert received.
After this test I received a number of unexpected alerts days and weeks apart yet when I investigated I was unable to verify that the whois command had been run (I had sysmon installed to assist with this)

I have recently wiped and rebuilt this PC with a fresh installation of Windows using a different hostname so surprised to have received yet another Canarytoken triggered alert email, it would be impossible for this alert to be valid as the host this was supposedly executed on in effect does not exist now neither does the canary registry entry exit in this build.

Curious as to why this is happening and dissuaded from using Canary tokens if I cannot be sure the alerts are valid.

I would appreciate any thoughts on this.

Thanks in advance

**Comment by cyb3n3tic** [comment]
Another Canarytoken triggered alert email received today stating hostname of the PC that no longer exists

**Comment by ranok** [comment]
Thanks @cyb3n3tic for the report, and sorry you ran into this. We have observed this behavior, where DNS resolvers and servers try to gain insights into the hostname by resolving it from other locations and providers to see if it may be malicious. This means there are "echos" of the query that will continue to alert.

We are addressing this by adding a random invocation ID to each lookup, and only alerting on that ID once. This will silence these duplicate alerts, but since the ID is randomly generated, another invocation of the same monitored binary will be alerted on. We'll close this issue once the fix is live, so you can regenerate the token and it shouldn't provide the same troubles.

**Comment by cyb3n3tic** [comment]
Thanks @ranok  for clarifying and glad to hear a fix is in the pipeline. Great work and great tool.

**Comment by cyb3n3tic** [comment]
Thanks for solving this @wleightond @ranok , great work - much appreciated
