### ISSUE TITLE
Token continues to trigger in unrelated PDFs

### ISSUE THREAD

**Issue by HDWorks** [thinkst/canarytokens#50]
I believe I've narrowed down the trigger but am not understanding the cause. I downloaded an pdf token to test and it successfully triggers when opened. However, I moved the tokenized pdf to another computer and placed it to be found by a colleague and resumed work on the original computer. When I open a link within an unrelated pdf, it is triggering the canarytoken again. Any clue how can I resolve this?

**Comment by jayjb** [comment]
Hi @HDWorks,

With the DNS based tokens, such as the PDF Canarytoken, we have seen a couple of mechanisms that may trigger it after it has been opened before. It is the reason that we recommend downloading a new one once it has triggered so that you can avoid false alerts. 

A few things that have caused multiple alerts of a previously triggered Canarytoken (DNS):
1. Cached DNS queries being tried again by something in the DNS resolver chain,
2. Programs caching the PDF (say in quick open or similar functions) and then retrying to open it as a method of making sure it is ready in case you want it opened. 

According to your description, I would think it is number 2. Try downloading a new PDF Canarytoken, don't trigger it and leave it where you know no one should be snooping.

**Comment by HDWorks** [comment]
Thanks for the explanation! I'll use a new one moving forward.
