### ISSUE TITLE
Blank page on startup

### ISSUE THREAD

**Issue by PlayerRock** [thinkst/canarytokens#602]
After installing, configuring and starting the containers in Ubuntu 22.04, when accessing the front end (example.com or example.com/generate), a blank page appears. The head of the html loads but in the body only the following loads:

```
<body>
  <div id="app"></div>
</body
```

In the docker log, the only errors it shows when accessing are:

switchboard  | 2024-11-06T10:59:42+0000 [canarytokens.channel_http#info] HTTP b'GET' on path b'/nest/assets/index-CHlc318J.css' did not correspond to a token. Error: /nest/assets/index-CHlc318J.css

switchboard  | 2024-11-06T11:00:03+0000 [canarytokens.channel_http#info] HTTP b'GET' on path b'/favicon.ico' did not correspond to a token. Error: /favicon.ico

I have tried to access from different browsers and operating systems with the same result.

**Comment by codigoartesano** [comment]
I have the same Issue :S , the pages is blank, but in the logs there are many activity

**Comment by thinkst-nick** [comment]
Hi @PlayerRock,

I noticed that the `thinkst/canarytokens_nginx` docker image hadn't been rebuilt since our move to Vue and the subsequent routing changes. This meant that the image had an old nginx.conf that did not handle the /nest/* routes correctly.

I've pushed a new image, could you please try `docker pull thinkst/canarytokens_nginx:latest` and then `docker compose up` again to see if it has solved your issue?

Thanks
Nick

**Comment by PlayerRock** [comment]
I've tried again with the changes you made and it works perfectly now.
Thanks.
