### ISSUE TITLE
Feature Request: Provide full URI for HTTP notifications

### ISSUE THREAD

**Issue by partigo** [thinkst/canarytokens#65]
For HTTP triggers, I can edit the URI so long as it includes the complete Canarytoken.  When I get a trigger report email, it includes only the Canarytoken itself.

It would be lovely if the URL which triggered the report was included in the email.  This could allow some additional information to be included, e.g. the name of the machine embedded in a custom URI.

Not clear if there is any need to sanitize the URI before including it in notification email, but likely not

**Comment by ajc133** [comment]
Couldn't this be accomplished by the user? Since they control the message displayed?

**Comment by partigo** [comment]
For a single use token on a single machine, then you are very right that it can perfectly go into the displayed message.

But it would be nice to take one generated token, leave the token trigger unchanged, and add per-machine identifying information to the URI.    If I imagine having thousands of machines, this allows me to statically or dynamically tweak to URI to identify the machine, or what was happening, or whatever.

**Comment by jayjb** [comment]
Hi @partigo,

Thanks for the suggestion. Its an interesting idea but as @ajc133 suggests it may give an attacker means to throw you off. If the url has identifying information, if an attacker realises its a canarytoken'ed url, she can start to misdirect you. 

In cases of thousands of servers, we would suggest creating thousands of new canarytokens and making sure that the "Memo" that you provide is useful to you so that you know which Canarytoken was tripped.
