### ISSUE TITLE
CanaryToken Windows folder issue

### ISSUE THREAD

**Issue by nodauf** [thinkst/canarytokens#68]
I deployed the canarytoken docker by following the step in the README.md. But when I generate the Windows folder token, the desktop.ini is using the main domain instead of the NXDOMAIN.

My configuration is:
```
CANARY_DOMAINS=canarytoken.mydomain.com
CANARY_NXDOMAINS=nx.canarytoken.mydomain.com 
```
and the desktop.ini is:
```
IconResource=\\%USERNAME%.%COMPUTERNAME%.%USERDOMAIN%.INI.5slbf8njoj1gh68ucbih9jm5f.canarytoken.mydomain.com\resource.dll
```

The token is never triggered but if I replace ``` canarytoken.mydomain.com ``` by ``` nx.canarytoken.mydomain.com ``` it's working.

**Comment by jayjb** [comment]
Hi @nodauf,

Would you mind letting me know what your DNS setup looks like?

**Comment by nodauf** [comment]
Hi,
Thank you for taking the time to reply.
My DNS server is on Windows Server 2016.

I have created the following records:
`nscanarytoken.mydomain.com A 10.0.0.1`
`canarytoken.mydomain.com A 10.0.0.1`

I have then created a NS record for `nxcanarytoken.mydomain.com` to use `nscanarytoken.mydomain.com.`

PS: I have updated my previous message. The NXDOMAINS is not `nx.canarytoken.mydomain.com` but `nxcanarytoken.mydomain.com`

**Comment by jayjb** [comment]
Hi @nodauf,

Thanks for the additional information. 

Can i ask you try changing your DNS records to:
`mydomain.com A 10.0.0.1`
`nscanarytoken.mydomain.com NS mydomain.com`
`canarytoken.mydomain.com NS mydomain.com`
`nxcanarytoken.mydomain.com NS mydomain.com`

The reason i am saying this is because the `NS` records specifies that the authoritative DNS server for that record i.e. `nscanarytoken.mydomain.com` is the authoritative DNS server for `nxcanarytoken.mydomain.com`. So any dns request that queries `nxcanarytoken.mydomain.com` is sent to `nscanarytoken.mydomain.com` which has the address `10.0.0.1`.

However, `canarytoken.mydomain.com` is not the authoritative DNS server for anyone because there is no NS record pointing towards it. 

Please let me know if that works for you.

**Comment by nodauf** [comment]
Hi @jayjb ,
Thank you for the help it's working 👍
